-- Registration codes for "Create Password" flow (replaces in-memory tokens).
-- Safe for load-balanced servers: any instance can validate codes from this table.
-- Run once: psql -f addRegistrationCodesTable.sql (or run this in your DB client)

CREATE TABLE IF NOT EXISTS public.registration_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email character varying(255) NOT NULL,
    code character varying(10) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    used_at timestamp with time zone
);

-- Lookup by code (and optionally email) when user submits the form
CREATE UNIQUE INDEX IF NOT EXISTS idx_registration_codes_code ON public.registration_codes (code);
CREATE INDEX IF NOT EXISTS idx_registration_codes_email ON public.registration_codes (email);
CREATE INDEX IF NOT EXISTS idx_registration_codes_expires_at ON public.registration_codes (expires_at);

COMMENT ON TABLE public.registration_codes IS 'One-time 6-char codes sent by email to complete registration; used instead of in-memory tokens for load balancing';
