-- Unified verifications table for registration email codes and phone verification sessions.
-- Run once: psql -f addVerificationsTable.sql (or run in your DB client)
-- This replaces the separate registration_codes and pending_phone_verifications tables in new code.

CREATE TABLE IF NOT EXISTS public.verifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email character varying(255),
    phone character varying(20),
    code character varying(10),
    password_hash character varying(255),
    kind character varying(50) NOT NULL, -- e.g. 'registration_email', 'phone_verify_session'
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    used_at timestamp with time zone
);

-- One-time registration codes sent by email
CREATE UNIQUE INDEX IF NOT EXISTS idx_verifications_registration_code_unique
    ON public.verifications (code)
    WHERE kind = 'registration_email';

CREATE INDEX IF NOT EXISTS idx_verifications_registration_code_lookup
    ON public.verifications (code)
    WHERE kind = 'registration_email' AND used_at IS NULL;

-- Short-lived phone verification sessions between Create Password and phone verification
CREATE INDEX IF NOT EXISTS idx_verifications_phone_session_lookup
    ON public.verifications (email, phone)
    WHERE kind = 'phone_verify_session' AND used_at IS NULL;

-- Expiration cleanup
CREATE INDEX IF NOT EXISTS idx_verifications_expires_at
    ON public.verifications (expires_at);

COMMENT ON TABLE public.verifications IS 'Short-lived verification artifacts (email registration codes and phone verification sessions), replacing registration_codes and pending_phone_verifications tables.';

